### ISSUE TITLE
how to upload only the documentation?

### ISSUE THREAD

**Issue by lucasafranio77** [wework/ray#1]
Hi,

My name is Lucas Afranio, and I am the president of a junior company in my college. And I really enjoyed how you documented your style guide and I'd like to use this documentation template. so I would like to know how to upload and modify it, what library did you use?

**Comment by adamraider** [comment]
Hey Lucas, thanks for your interest.

The documentation is in the packages/docs-app directory and the pages are sources from the docs/ directory in the root.

**Comment by adamraider** [comment]
LMK if you have any other questions, otherwise please close out the issue
