### ISSUE TITLE
BEM Convention not followed everywhere

### ISSUE THREAD

**Issue by grmoon** [wework/ray#147]
If this project is meant to follow the BEM class naming style, it doesn't appear to do so it some core places where modifiers are treated as standalone blocks or elements. A couple examples that come to mind are the grid and the text styles. 

According to [BEM naming guidelines](http://getbem.com/naming/), modifiers like `ray-grid__cell--span-4` or `ray-text--h4` should not be the only classes on an element. Instead the elements should have the classes `ray-grid__cell ray-grid__cell--span-4` and `ray-text ray-text--h4` respectively.

If adherence to BEM is not a priority then this issue can just be closed. If it is we should figure out how to update the implementation to reflect that.

**Comment by adamraider** [comment]
Strict adherence to bem is not a priority so long as the classnames are relatively intuitive. Do you feel there is an issue with readability?

**Comment by adamraider** [comment]
@cmugla @i8ramin Thoughts?

**Comment by adamraider** [comment]
This would require a large scale refactor, I'm going to close for now, but if other maintainers feel this is important lets revisit
