### ISSUE TITLE
<i> inside .ray-running-text should be italicized

### ISSUE THREAD

**Issue by modelm** [wework/ray#153]
Chris Palermino reported this problem for posts migrated from Creator to Ideas.

Here's an example: https://www.wework.com/ideas/how-to-hold-effective-meetings

The text `The Surprising Science of Meetings` should be italicized.

Related: https://github.com/wework/ray/pull/96

**Comment by adamraider** [comment]
Thanks for the bug report, I've submitted a PR to address!
