### ISSUE TITLE
Vertical Spacing

### ISSUE THREAD

**Issue by danaballasy** [wework/ray#18]
128px spacing should be 96px

**Comment by adamraider** [comment]
Nothing in the system uses 128px spacing. This is a modification for https://github.com/weconnect/www-website.

**Comment by cmugla** [comment]
@adamraider this is in reference to the spacing docs:
![Screen Shot 2019-04-30 at 3 54 22 PM](https://user-images.githubusercontent.com/19141291/56989356-4169dc80-6b60-11e9-9fee-4c63af6ee1e9.png)

Also, looks like there is no [variable](https://github.com/wework/ray/blob/master/packages/core/src/global/spacing/_spacing.scss) right now that supports `96px`

**Comment by adamraider** [comment]
I see
