### ISSUE TITLE
Checkbox focus state is cut off

### ISSUE THREAD

**Issue by alanfriedman** [wework/ray#78]
Would be good to add some left padding so the active state blurry outline thing doesn't get cut off:

Before:

<img width="196" alt="Screen Shot 2019-05-08 at 11 35 31 AM" src="https://user-images.githubusercontent.com/1093435/57388236-c7e87480-7185-11e9-91b3-5ccaed9f65ef.png">

After:

<img width="188" alt="Screen Shot 2019-05-08 at 11 35 50 AM" src="https://user-images.githubusercontent.com/1093435/57388245-cd45bf00-7185-11e9-8b7c-7cb9c78ca09f.png">

**Comment by adamraider** [comment]
You could add some bespoke padding to your form @alanfriedman

**Comment by adamraider** [comment]
This isn't really a bug i dont think, you should avoid using overflow: hidden in this case
